service: eventdriven-dataflow

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  memorySize: 512 # optional, in MB, default is 1024; can be 128, 256, 512, 1024, 2048, 4096, 5120, ...
  timeout: 10 # optional, in seconds, default is 6
  ecr:
    images:
      etl:
        path: ./etl
      ml:
        path: ./ml
      healthcheck:
        path: ./healthcheck
      s3_event_flow:
        path: ./s3_event_flow
      s3_reactive_flow:
        path: ./s3_reactive_flow

  environment:
    PREFECT_HOME: /tmp/.prefect
    PREFECT_API_KEY: prefectapikey
    PREFECT_API_URL: 'https://app.prefect.cloud/account/0ff44498-d380-4d7b-bd68-9b52da03823f/workspace/f579e720-7969-4ab8-93b7-2dfa784903e6'

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - athena:*
            - glue:*
            - s3:*
          Resource: "*"

functions:
  etl:
    image:
      name: etl
    events:
      - schedule: rate(60 minutes)

  healthcheck:
    image:
      name: healthcheck
    events:
      - schedule: rate(30 minutes)

  ml:
    image:
      name: ml
    events:
      - schedule: rate(15 minutes)

  s3_event_flow:
    image:
      name: s3_event_flow
    events:
      - schedule: rate(1 minute)

  s3_reactive_flow:
    image:
      name: s3_reactive_flow
    events:
      - s3:
          bucket: prefectdata
          event: s3:ObjectCreated:*
          rules:
            - prefix: timeseries/
            - suffix: .snappy.parquet
          existing: true
